import { Category, Product } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    category_id: 1,
    name: 'Hộp quà Tết',
    slug: 'hop-qua-tet',
    description: 'Hộp quà đặc sản ba miền cao cấp, kèm thiệp chúc Tết viết tay',
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80',
    sort_order: 1,
    is_active: true,
  },
  {
    category_id: 2,
    name: 'Bánh mứt',
    slug: 'banh-mut',
    description: 'Bánh, kẹo, mứt truyền thống sum vầy ngày Tết',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    sort_order: 2,
    is_active: true,
  },
  {
    category_id: 3,
    name: 'Trà & Cà phê',
    slug: 'tra-ca-phe',
    description: 'Trà Thái Nguyên, trà sen Tây Hồ, cà phê Tây Nguyên đậm đà',
    image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    sort_order: 3,
    is_active: true,
  },
  {
    category_id: 4,
    name: 'Hạt & Đồ khô',
    slug: 'hat-kho',
    description: 'Hạt điều rang muối, mắc ca, khô bò cay nồng nhâm nhi',
    image_url: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600&auto=format&fit=crop&q=80',
    sort_order: 4,
    is_active: true,
  },
  {
    category_id: 5,
    name: 'Gia vị & Nước chấm',
    slug: 'gia-vi',
    description: 'Nước mắm Phú Quốc, tỏi Lý Sơn, gia vị tinh hoa vùng miền',
    image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    sort_order: 5,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    product_id: 1,
    category_id: 1,
    name: 'Hộp quà Tết An Khang 2027',
    slug: 'hop-qua-tet-an-khang',
    short_description: 'Hộp 4 món: trà Thái Nguyên, mứt dừa Bến Tre, hạt điều, mè xửng Huế',
    description: 'Hộp quà Tết An Khang mang biểu trưng cho một năm mới an lành, sung túc và bình an. Được tuyển chọn thủ công từ những đặc sản trứ danh 3 miền.',
    origin: 'Ba miền',
    producer: 'Hương Quê Artisan',
    region: 'ba_mien',
    unit: 'hộp',
    price: 349000,
    compare_at_price: 399000,
    stock: 120,
    sold_count: 85,
    rating_avg: 5.0,
    rating_count: 32,
    thumbnail_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 2,
    category_id: 1,
    name: 'Hộp quà Tết Phúc Lộc Đoàn Viên',
    slug: 'hop-qua-tet-phuc-loc',
    short_description: 'Hộp 6 món đặc sản ba miền thượng hạng, kèm thiệp chúc Tết viết tay',
    description: 'Tuyệt phẩm quà tặng cho gia đình và đối tác với thiết kế trang nhã, chất liệu giấy gân cao cấp phối ánh vàng kim sang trọng.',
    origin: 'Ba miền',
    producer: 'Hương Quê Artisan',
    region: 'ba_mien',
    unit: 'hộp',
    price: 649000,
    compare_at_price: 720000,
    stock: 100,
    sold_count: 142,
    rating_avg: 4.9,
    rating_count: 48,
    thumbnail_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 3,
    category_id: 1,
    name: 'Hộp quà Tết Thịnh Vượng (Hộp Gỗ VIP)',
    slug: 'hop-qua-tet-thinh-vuong',
    short_description: 'Hộp gỗ sơn mài 8 món cao cấp: trà sen Tây Hồ, mắc ca, nước mắm cốt Phú Quốc',
    description: 'Hộp gỗ tự nhiên chạm khắc họa tiết Tết truyền thống, chứa đựng 8 thức quà cao cấp nhất từ các vùng miền Việt Nam.',
    origin: 'Ba miền',
    producer: 'Hương Quê Artisan',
    region: 'ba_mien',
    unit: 'hộp gỗ',
    price: 1190000,
    compare_at_price: 1350000,
    stock: 45,
    sold_count: 67,
    rating_avg: 5.0,
    rating_count: 24,
    thumbnail_url: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 4,
    category_id: 1,
    name: 'Hộp quà Tết Tinh Hoa Bắc Bộ',
    slug: 'hop-qua-tet-huong-bac',
    short_description: 'Trà Tân Cương thượng hạng, ô mai mơ gừng Hà Nội, bánh cốm gia truyền',
    description: 'Mang trọn vẹn nét thanh tao, cổ kính và ấm nồng của đất kinh kỳ nghìn năm văn hiến về trong mái ấm ngày đầu xuân.',
    origin: 'Hà Nội',
    producer: 'Đặc sản Thăng Long',
    region: 'bac',
    unit: 'hộp',
    price: 559000,
    compare_at_price: 620000,
    stock: 80,
    sold_count: 53,
    rating_avg: 4.8,
    rating_count: 19,
    thumbnail_url: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 5,
    category_id: 1,
    name: 'Hộp quà Tết Hương Vị Xứ Cố Đô',
    slug: 'hop-qua-tet-huong-trung',
    short_description: 'Mè xửng Huế, kẹo cu đơ Hà Tĩnh, tỏi cô đơn Lý Sơn, cà phê Buôn Ma Thuột',
    description: 'Đậm đà tình nghĩa miền Trung mộc mạc và chân thành, thức quà thơm ngon nức lòng người thưởng thức.',
    origin: 'Huế',
    producer: 'Đặc sản Cố Đô',
    region: 'trung',
    unit: 'hộp',
    price: 499000,
    compare_at_price: 560000,
    stock: 75,
    sold_count: 41,
    rating_avg: 4.7,
    rating_count: 15,
    thumbnail_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 6,
    category_id: 1,
    name: 'Hộp quà Tết Phương Nam Trù Phú',
    slug: 'hop-qua-tet-huong-nam',
    short_description: 'Mứt dừa sáp Bến Tre, bánh pía Sóc Trăng, hạt điều rang muối Bình Phước',
    description: 'Đại diện cho sự trù phú, thơm ngọt phù sa và hào sảng của vùng đất Nam Bộ hiền hòa.',
    origin: 'Bến Tre',
    producer: 'Đặc sản Miền Tây',
    region: 'nam',
    unit: 'hộp',
    price: 459000,
    compare_at_price: 510000,
    stock: 90,
    sold_count: 78,
    rating_avg: 4.9,
    rating_count: 27,
    thumbnail_url: 'https://images.unsplash.com/photo-1608755728617-aefab37d2edd?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 7,
    category_id: 2,
    name: 'Ô mai mơ gừng phố cổ Hà Nội 500g',
    slug: 'o-mai-mo-gung-ha-noi-500g',
    short_description: 'Ô mai mơ dẻo thơm, vị chua ngọt thanh tao, cay nồng ấm áp của gừng già',
    description: 'Món ăn vặt trứ danh ngày Tết Hà Thành. Vị chua thanh, dẻo dai hòa quyện vị cay the của gừng sợi.',
    origin: 'Hà Nội',
    producer: 'Ô Mai Cổ Truyền',
    region: 'bac',
    unit: 'hộp 500g',
    price: 150000,
    compare_at_price: null,
    stock: 150,
    sold_count: 110,
    rating_avg: 4.8,
    rating_count: 36,
    thumbnail_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 8,
    category_id: 2,
    name: 'Bánh cốm Hàng Than hộp 10 chiếc',
    slug: 'banh-com-ha-noi-hop-10',
    short_description: 'Vỏ cốm xanh non dẻo quánh, nhân đậu xanh sên đường dừa ngọt dịu',
    description: 'Đặc sản làm quà nức tiếng Hà Nội, bánh mềm mịn, ngát hương hoa bưởi thoang thoảng.',
    origin: 'Hà Nội',
    producer: 'Bánh Cốm Hà Nội',
    region: 'bac',
    unit: 'hộp 10 chiếc',
    price: 85000,
    compare_at_price: null,
    stock: 120,
    sold_count: 95,
    rating_avg: 4.7,
    rating_count: 22,
    thumbnail_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 9,
    category_id: 2,
    name: 'Mè xửng dẻo Cung Đình Huế 250g',
    slug: 'me-xung-hue-250g',
    short_description: 'Kẹo mè xửng dẻo bùi hạt mè rang vàng óng, đậu phộng béo giòn thơm',
    description: 'Hương vị cung đình xưa, kẹo mềm dẻo không dính răng, vị ngọt thanh tao nhấp ngụm trà sen.',
    origin: 'Huế',
    producer: 'Mè Xửng Cung Đình',
    region: 'trung',
    unit: 'hộp 250g',
    price: 45000,
    compare_at_price: null,
    stock: 200,
    sold_count: 180,
    rating_avg: 4.9,
    rating_count: 51,
    thumbnail_url: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 10,
    category_id: 2,
    name: 'Kẹo Cu Đơ Hà Tĩnh hộp 400g',
    slug: 'keo-cu-do-ha-tinh-400g',
    short_description: 'Bánh tráng nướng giòn kẹp mạch nha cô đặc, gừng tươi và đậu phộng ta',
    description: 'Món kẹo giòn rụm bên ngoài, dẻo quánh bên trong, vị cay the của gừng át đi vị ngọt gắt.',
    origin: 'Hà Tĩnh',
    producer: 'Đặc sản Cu Đơ',
    region: 'trung',
    unit: 'gói 400g',
    price: 60000,
    compare_at_price: null,
    stock: 140,
    sold_count: 65,
    rating_avg: 4.6,
    rating_count: 18,
    thumbnail_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 11,
    category_id: 2,
    name: 'Bánh Pía sầu riêng trứng muối Sóc Trăng',
    slug: 'banh-pia-sau-rieng-soc-trang',
    short_description: 'Vỏ ngàn lớp mỏng tang, nhân sầu riêng tươi đậm đà cùng trứng muối béo ngậy',
    description: 'Bánh Pía truyền thống Sóc Trăng với lớp vỏ mềm mỏng, nhân sầu riêng nguyên chất thơm nức.',
    origin: 'Sóc Trăng',
    producer: 'Bánh Pía Tân Huê Viên',
    region: 'nam',
    unit: 'hộp 4 chiếc',
    price: 75000,
    compare_at_price: 85000,
    stock: 160,
    sold_count: 220,
    rating_avg: 5.0,
    rating_count: 89,
    thumbnail_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 12,
    category_id: 2,
    name: 'Mứt dừa non hoa sen Bến Tre 500g',
    slug: 'mut-dua-non-ben-tre-500g',
    short_description: 'Dừa non sên đường phèn thanh mát, mềm dẻo không gắt, tạo hình cánh hoa sen',
    description: 'Làm từ cùi dừa non tinh tuyển, mềm ngọt tự nhiên, không hóa chất phẩm màu.',
    origin: 'Bến Tre',
    producer: 'Mứt Quê Hương',
    region: 'nam',
    unit: 'hộp 500g',
    price: 95000,
    compare_at_price: null,
    stock: 180,
    sold_count: 135,
    rating_avg: 4.8,
    rating_count: 42,
    thumbnail_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 13,
    category_id: 3,
    name: 'Trà Đinh Tân Cương Thái Nguyên 200g',
    slug: 'tra-tan-cuong-thai-nguyen-200g',
    short_description: 'Tuyển chọn từ những búp trà đinh non nhất, vị chát dịu, hậu ngọt sâu lắng',
    description: 'Đệ nhất danh trà Việt Nam. Nước xanh sóng sánh, hương cốm non thoảng đưa, đậm đà vị trà Việt.',
    origin: 'Thái Nguyên',
    producer: 'Hợp Tác Xã Trà Thái',
    region: 'bac',
    unit: 'gói 200g',
    price: 180000,
    compare_at_price: 210000,
    stock: 110,
    sold_count: 160,
    rating_avg: 5.0,
    rating_count: 65,
    thumbnail_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 14,
    category_id: 3,
    name: 'Trà Sen Tây Hồ ướp bông tươi Thăng Long 100g',
    slug: 'tra-sen-tay-ho-100g',
    short_description: 'Nghệ thuật ướp trà sen trăm năm, hương sen Bách Diệp nồng nàn thanh quý',
    description: 'Mỗi ấm trà cần đến hàng trăm bông hoa sen Bách Diệp hồ Tây sớm mai để lưu giữ trọn vẹn hương sắc thiên nhiên.',
    origin: 'Hà Nội',
    producer: 'Nghệ Nhân Sen Tây Hồ',
    region: 'bac',
    unit: 'hộp 100g',
    price: 450000,
    compare_at_price: 520000,
    stock: 25,
    sold_count: 40,
    rating_avg: 5.0,
    rating_count: 18,
    thumbnail_url: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 15,
    category_id: 3,
    name: 'Cà phê Robusta Mộc Buôn Ma Thuột 500g',
    slug: 'ca-phe-robusta-buon-ma-thuot-500g',
    short_description: 'Hạt cà phê chín đỏ trên đất đỏ Bazan, rang mộc đậm đà nguyên bản',
    description: 'Vị đắng đằm thắm, hương thơm nồng nàn lan tỏa, khơi gợi cảm hứng ngày đầu xuân năm mới.',
    origin: 'Đắk Lắk',
    producer: 'Ban Me Coffee',
    region: 'trung',
    unit: 'gói 500g',
    price: 160000,
    compare_at_price: null,
    stock: 140,
    sold_count: 98,
    rating_avg: 4.8,
    rating_count: 31,
    thumbnail_url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 16,
    category_id: 3,
    name: 'Trà Atiso túi lọc nguyên chất Đà Lạt',
    slug: 'tra-atiso-da-lat-100-tui',
    short_description: 'Chiết xuất từ hoa atiso Đà Lạt, thanh nhiệt giải độc, tốt cho sức khỏe ngày Tết',
    description: 'Thức uống bổ dưỡng cho ngày Tết ăn nhiều bánh mứt và món dầu mỡ, vị ngọt mát dịu dàng.',
    origin: 'Lâm Đồng',
    producer: 'Ladophar Đà Lạt',
    region: 'trung',
    unit: 'hộp 100 túi',
    price: 120000,
    compare_at_price: null,
    stock: 130,
    sold_count: 75,
    rating_avg: 4.7,
    rating_count: 24,
    thumbnail_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 17,
    category_id: 4,
    name: 'Hạt điều rang muối Bình Phước loại A 500g',
    slug: 'hat-dieu-rang-muoi-binh-phuoc-500g',
    short_description: 'Hạt điều nguyên hạt còn vỏ lụa, rang củi thủ công thơm giòn béo ngậy',
    description: 'Hạt điều Bình Phước trứ danh, hạt to đều, giòn rụm béo bùi, vị mặn nhẹ của muối tinh.',
    origin: 'Bình Phước',
    producer: 'Hạt Việt Farm',
    region: 'nam',
    unit: 'hũ 500g',
    price: 185000,
    compare_at_price: 210000,
    stock: 190,
    sold_count: 310,
    rating_avg: 5.0,
    rating_count: 112,
    thumbnail_url: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&auto=format&fit=crop&q=80',
    is_featured: true,
    is_active: true,
  },
  {
    product_id: 18,
    category_id: 4,
    name: 'Hạt Mắc Ca nứt vỏ Tây Nguyên 500g',
    slug: 'hat-mac-ca-dak-nong-500g',
    short_description: 'Nữ hoàng các loại hạt, vị ngọt bùi tự nhiên giàu dinh dưỡng, kèm dụng cụ tách vỏ',
    description: 'Hạt mắc ca Tây Nguyên sấy chín tự nhiên, giữ trọn hàm lượng dầu và dưỡng chất quý giá.',
    origin: 'Đắk Nông',
    producer: 'Macca Tây Nguyên',
    region: 'trung',
    unit: 'túi 500g',
    price: 210000,
    compare_at_price: null,
    stock: 150,
    sold_count: 88,
    rating_avg: 4.9,
    rating_count: 29,
    thumbnail_url: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 19,
    category_id: 4,
    name: 'Khô bò miếng cay Gia Lai 250g',
    slug: 'kho-bo-gia-lai-250g',
    short_description: 'Thịt bò tươi tẩm ướp mật ong rừng và ớt xiêm cay nồng thơm ngất ngây',
    description: 'Thịt bò bắp tươi ngon nguyên thớ sấy khô vừa tới, mềm không dai, vị cay ngọt đậm đà.',
    origin: 'Gia Lai',
    producer: 'Bò Khô Cao Nguyên',
    region: 'trung',
    unit: 'gói 250g',
    price: 165000,
    compare_at_price: null,
    stock: 85,
    sold_count: 145,
    rating_avg: 4.8,
    rating_count: 53,
    thumbnail_url: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
  {
    product_id: 20,
    category_id: 4,
    name: 'Lạp xưởng tôm Mai Quế Lộ Cần Đước 500g',
    slug: 'lap-xuong-can-duoc-500g',
    short_description: 'Lạp xưởng đặc sản Long An, thơm lừng mùi rượu Mai Quế Lộ gia truyền',
    description: 'Tỉ lệ thịt nạc và tôm cao, vị ngọt tự nhiên hòa quyện gia vị truyền thống thơm lừng mâm cỗ Tết.',
    origin: 'Long An',
    producer: 'Lạp Xưởng Cần Đước',
    region: 'nam',
    unit: 'gói 500g',
    price: 170000,
    compare_at_price: 195000,
    stock: 110,
    sold_count: 82,
    rating_avg: 4.9,
    rating_count: 34,
    thumbnail_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    is_featured: false,
    is_active: true,
  },
];
